// Failed to get sources. Instead, stub sources have been generated by the disassembler.
// Implementation of methods is unavailable.
public class WeatherApp {

    public WeatherApp() {
    }

    public static double getWeatherData(java.lang.String arg0) {
        return 0;
    }

    public static double getWindSpeedData(java.lang.String arg0) {
        return 0;
    }

    public static double getPressureData(java.lang.String arg0) {
        return 0;
    }

    public static void main(java.lang.String[] arg0) {
    }
}